version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app

hooks:
  BeforeInstall:
    - location: scripts/install_docker.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/stop_old_container.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_new_container.sh
      timeout: 300
      runas: root
