version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env  # Mount the .env file
    command:  >
      sh -c "
      pip install -r requirements.txt &&

      python manage.py collectstatic --no-input &&
      python manage.py migrate auth &&
      python manage.py migrate admin &&
      python manage.py migrate sessions &&
      python manage.py migrate &&
      python manage.py loaddata backup.json &&
      gunicorn base.wsgi:application --bind 0.0.0.0:8000
      "
    networks:
      - server-side
    volumes:
      - json-data:/app
    ports:
      - "8000:8000"
    depends_on:
      - database

  nginx:
    image: nginx:latest
    volumes:
      - /etc/ssl/cloudflare/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/ssl/cloudflare/cloudflare.crt:/etc/ssl/cloudflare/cloudflare.crt:ro  # SSL certificate
      - /etc/ssl/cloudflare/cloudflare.key:/etc/ssl/cloudflare/cloudflare.key:ro  # SSL certificate key
      - static_volume:/vol/static
      - media_volume:/vol/media
    ports:
      - "80:80"  # Expose port 80 for HTTP traffic
      - "443:443"  # HTTPS traffic
    depends_on:
      - backend

  database:
    image: postgres
    shm_size: 500mb
    environment:
      POSTGRES_PASSWORD: Jz23dds/1!@##!@.23
    networks:
      - server-side
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  server-side: {}

volumes:
  db-data: {}
  json-data: {}
  static_volume: {}  # Declare named volume for static files
  media_volume: {}   # Declare named volume for media files
