version: "3.8"

services:
  backend:
    build: .
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
    networks:
      - server-side
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - database

  database:
    image: postgres
    shm_size: 200mb
    environment:
      POSTGRES_PASSWORD: Jz23dds/1!@##!@.23
    networks:
      - server-side
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  server-side: {}

volumes:
  db-data: {}
