# Generated by Django 4.1.7 on 2023-04-25 17:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import project.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('created', models.DateField(validators=[project.models.validate_date])),
                ('client', models.CharField(default='None', max_length=100)),
                ('thumbnail', models.ImageField(upload_to='projects')),
                ('domain', models.CharField(choices=[('wb', 'Web development'), ('ds', 'Data science'), ('uix', 'UI/UX design'), ('ml', 'Machine learning'), ('cs', 'Cyber security'), ('rd', 'Random project')], max_length=3)),
                ('role', models.CharField(choices=[('fd', 'Frontend developer'), ('bd', 'Backend developer'), ('fs', 'Fullstack developer'), ('uix', 'UI/UX designer'), ('ds', 'Data scientist'), ('sd', 'Software developer')], default='bd', max_length=3)),
                ('type', models.CharField(choices=[('js', 'Joint project'), ('so', 'Solo')], default='so', max_length=3)),
                ('live_url', models.URLField(blank=True)),
                ('figma_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('project', models.ManyToManyField(related_name='tags', to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to='projects')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='project.project')),
            ],
        ),
    ]
