# Generated by Django 4.1.7 on 2023-05-07 07:53

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='projects'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='projects'),
        ),
    ]
