# Generated by Django 4.1.7 on 2023-04-25 17:39

import about.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('w', 'work'), ('e', 'education')], max_length=1)),
                ('start_date', models.DateField(validators=[about.models.validate_date])),
                ('end_date', models.DateField(blank=True, null=True, validators=[about.models.validate_date])),
                ('institution', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('about', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Honour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('a', 'award'), ('c', 'certification')], max_length=1)),
                ('banner', models.ImageField(upload_to='about')),
                ('title', models.CharField(max_length=150)),
                ('about', models.CharField(max_length=150)),
                ('issue_date', models.DateField(validators=[about.models.validate_date])),
                ('sub_about', models.CharField(blank=True, max_length=150)),
                ('certification_no', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
