# Generated by Django 4.1.7 on 2023-05-09 00:56

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honour',
            name='banner',
            field=models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='about'),
        ),
    ]
